version: '3'
services:
  mywork:
    build: .
    ports:
    - "8080:8080"
    links:
    - some-redis:
    - some-mysql:
  some-redis:
    image: redis
    ports:
    - "6379:6379"
  some-mysql:
    build: ./mysql
    ports:
    - "3306:3306"
    
